# This file was generated by https://github.com/kamilchm/go2nix v1.2.0
[
  {
    goPackagePath = "github.com/djmitche/shquote";
    fetch = {
      type = "git";
      url = "https://github.com/djmitche/shquote";
      rev = "c04fd6eb8242150b80b85185f3cd177c9d4dbfdb";
      sha256 = "00klpg7m5f95cz00gs4yinf50mh48xsz7zlxq5z508ybpv0yrvr1";
    };
  }
  {
    goPackagePath = "github.com/kardianos/osext";
    fetch = {
      type = "git";
      url = "https://github.com/kardianos/osext";
      rev = "ae77be60afb1dcacde03767a8c37337fad28ac14";
      sha256 = "056dkgxrqjj5r18bnc3knlpgdz5p3yvp12y4y978hnsfhwaqvbjz";
    };
  }
  {
    goPackagePath = "github.com/orivej/e";
    fetch = {
      type = "git";
      url = "https://github.com/orivej/e.git";
      rev = "1dd70a0111a57294488955d7ce7ef69fd10e850f";
      sha256 = "08hs3bvxxw052cmfxh1hixdpx86zj4ac9grbrlvfmyxy8q51csr9";
    };
  }
  {
    goPackagePath = "golang.org/x/sys";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/sys";
      rev = "dbc2be9168a660ef302e04b6ff6406de6f967473";
      sha256 = "1hz9d7wnxwlvhlgmqrxjdx9fihx30f9ww6ir2l74l8ping1g6w1j";
    };
  }
]
