# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
[
  {
    goPackagePath = "github.com/djmitche/shquote";
    fetch = {
      type = "git";
      url = "https://github.com/djmitche/shquote";
      rev = "c04fd6eb8242150b80b85185f3cd177c9d4dbfdb";
      sha256 = "00klpg7m5f95cz00gs4yinf50mh48xsz7zlxq5z508ybpv0yrvr1";
    };
  }
  {
    goPackagePath = "github.com/kardianos/osext";
    fetch = {
      type = "git";
      url = "https://github.com/kardianos/osext";
      rev = "ae77be60afb1dcacde03767a8c37337fad28ac14";
      sha256 = "056dkgxrqjj5r18bnc3knlpgdz5p3yvp12y4y978hnsfhwaqvbjz";
    };
  }
  {
    goPackagePath = "github.com/orivej/e";
    fetch = {
      type = "git";
      url = "https://github.com/orivej/e.git";
      rev = "ac3492690fda471c5eab817efd86badf5c3ac158";
      sha256 = "11jizr28kfkr6zscjxg95pqi6cjp08aqnhs41sdhc98nww78ilkr";
    };
  }
  {
    goPackagePath = "golang.org/x/net";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/net";
      rev = "3673e40ba22529d22c3fd7c93e97b0ce50fa7bdd";
      sha256 = "0vx7mz18p480p7fh0w5jv6mfdbsswrlac1sz4i705q7q7ygz59lm";
    };
  }
  {
    goPackagePath = "golang.org/x/sys";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/sys";
      rev = "bd9dbc187b6e1dacfdd2722a87e83093c2d7bd6e";
      sha256 = "0zj8s3q2fznmap1nfr8pv4hz8xqixmkyhr6slq4baf8rvcb4mvbj";
    };
  }
  {
    goPackagePath = "golang.org/x/text";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/text";
      rev = "0605a8320aceb4207a5fb3521281e17ec2075476";
      sha256 = "1pak7q9ivwxh5bnjk00pkrs9ri9vmbyccvza56fl6138w397h49j";
    };
  }
]
