# This file was generated by https://github.com/kamilchm/go2nix v1.2.0
[
  {
    goPackagePath = "github.com/djmitche/shquote";
    fetch = {
      type = "git";
      url = "https://github.com/djmitche/shquote";
      rev = "c04fd6eb8242150b80b85185f3cd177c9d4dbfdb";
      sha256 = "00klpg7m5f95cz00gs4yinf50mh48xsz7zlxq5z508ybpv0yrvr1";
    };
  }
  {
    goPackagePath = "github.com/orivej/e";
    fetch = {
      type = "git";
      url = "https://github.com/orivej/e.git";
      rev = "1dd70a0111a57294488955d7ce7ef69fd10e850f";
      sha256 = "08hs3bvxxw052cmfxh1hixdpx86zj4ac9grbrlvfmyxy8q51csr9";
    };
  }
  {
    goPackagePath = "golang.org/x/sys";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/sys";
      rev = "ea9bcade75cb975a0b9738936568ab388b845617";
      sha256 = "0z7mpb1r5hcfbpw2z355vflwcd3cfp5pssz7q14sczh33rddp10g";
    };
  }
]
